name: CI Pipeline

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run type-check

      - name: Lint
        run: bun run lint

      - name: Run tests
        run: bun run test
        env:
          CI: true
          NODE_ENV: test
          # NOTE: GitHub Actions secrets are not available for private repos on free tier
          # Using hardcoded Neon test database URL until repo is public or upgraded
          # TODO: Move to GitHub secrets when available: ${{ secrets.NEON_TEST_DATABASE_URL }}
          NEON_TEST_DATABASE_URL: "postgresql://neondb_owner:npg_UcW7ZvSF1Gko@ep-purple-heart-aet8dac5-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
          NETLIFY_DATABASE_URL: "postgresql://neondb_owner:npg_UcW7ZvSF1Gko@ep-purple-heart-aet8dac5-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
          BETTER_AUTH_SECRET: test-secret-key-for-ci-minimum-32-characters-long
          DEPLOY_PRIME_URL: http://localhost:3000

      - name: Build
        run: bun run build
        env:
          NODE_ENV: production
          # NOTE: Using test database for build validation (no actual data operations)
          # Production builds in Netlify use different database via environment variables
          NETLIFY_DATABASE_URL: "postgresql://neondb_owner:npg_UcW7ZvSF1Gko@ep-shiny-meadow-aeijkztn-pooler.c-2.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
          BETTER_AUTH_SECRET: build-secret-key-minimum-32-characters-long
          DEPLOY_PRIME_URL: https://example.com
