name: CI Pipeline

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Rebuild native modules
        run: bun rebuild better-sqlite3

      - name: Type check
        run: bun run type-check

      - name: Lint
        run: bun run lint

      - name: Run tests
        run: bun run test
        env:
          NODE_ENV: test
          DATABASE_URL: file:./test.db
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_APP_URL: http://localhost:3000

      - name: Build
        run: bun run build
        env:
          NODE_ENV: production
          DATABASE_URL: file:./build.db
          BETTER_AUTH_SECRET: build-secret-key
          NEXT_PUBLIC_APP_URL: https://example.com
