name: Run Tests

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: cd apps/web && bun run test:run
        env:
          CI: true
          # Use Neon test database from GitHub secrets
          NEON_TEST_DATABASE_URL: ${{ secrets.NEON_TEST_DATABASE_URL }}
          NETLIFY_DATABASE_URL: ${{ secrets.NEON_TEST_DATABASE_URL }}
